/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.udc.asociacioncomercios.GUI.Frames;

import com.udc.asociacioncomercios.app.Datos;
import com.udc.asociacioncomercios.elementos.Comercio;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author cpala
 */
public class FormRelZonaComercio extends javax.swing.JFrame {

    /**
     * Creates new form CrearComercio
     */
    
    Datos d = Datos.getD();

    private int posicion;
    
    public FormRelZonaComercio() {
        initComponents();
    }
    
    public FormRelZonaComercio(int posicion) {
        this.posicion = posicion;
        d.llenarSelectComercio();
        initComponents();
    }
    

    /**
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        nombreZona = new javax.swing.JTextField();
        codigoZona = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        comercio = new javax.swing.JComboBox<>();
        addComercio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAsociacionComercio = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setText("Asignacion de comercios");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        labelCodigo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelCodigo.setText("Codigo");

        nombreZona.setEditable(false);
        nombreZona.setText(d.getListaZonas().get(posicion).getNombre());
        nombreZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreZonaActionPerformed(evt);
            }
        });

        codigoZona.setEditable(false);
        codigoZona.setText(d.getListaZonas().get(posicion).getCodigo());
        codigoZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoZonaActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setText("comercio");

        comercio.setModel(d.getSelectComercios());
        comercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comercioActionPerformed(evt);
            }
        });

        addComercio.setText("Agregar");
        addComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComercioActionPerformed(evt);
            }
        });

        tAsociacionComercio.setModel(d.getModAsComercio());
        tAsociacionComercio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tAsociacionComercioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tAsociacionComercio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(labelCodigo))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoZona)
                            .addComponent(nombreZona))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(salir)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(51, 51, 51)
                                .addComponent(comercio, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(addComercio)))
                        .addContainerGap(72, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(codigoZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addComercio))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(salir)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void nombreZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreZonaActionPerformed

    private void codigoZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoZonaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void addComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComercioActionPerformed
        String nuevoComercio = (String) comercio.getSelectedItem();
        Comercio nc = d.buscarComercioPorNombre(nuevoComercio);
        d.getListaZonas().get(posicion).asignarComercio(nc);
        actualizarTabla();
    }//GEN-LAST:event_addComercioActionPerformed

    private void tAsociacionComercioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tAsociacionComercioMouseClicked
        int f = tAsociacionComercio.rowAtPoint(evt.getPoint());
        int c = tAsociacionComercio.columnAtPoint(evt.getPoint());
        
        if(c == 4){
            int posicionEncontrada = -1;
            String n = tAsociacionComercio.getValueAt(f, 0).toString();
            // Bucle foreach para buscar el comercio por nombre
            for (int i = 0; i < d.getListaZonas().get(posicion).getComerciosAsociados().size(); i++) {
                Comercio comercio = d.getListaZonas().get(posicion).getComerciosAsociados().get(i);
                if (comercio.getNombre().equalsIgnoreCase(n)) {
                    // El nombre del comercio coincide, guarda la posición y sal del bucle
                    posicionEncontrada = i;
                    break;
                }
            }
            if (posicionEncontrada != -1) {
                d.getListaZonas().get(posicion).getComerciosAsociados().remove(posicionEncontrada);
                actualizarTabla();
            }     
        }
    }//GEN-LAST:event_tAsociacionComercioMouseClicked

    private void comercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comercioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comercioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRelZonaComercio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRelZonaComercio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRelZonaComercio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRelZonaComercio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRelZonaComercio().setVisible(true);
            }
        });
    }
    
     private boolean validarCampos(JTextField campoNombre,JTextField campoCodigo){
            // Validar que los campos no estén vacíos
    if (campoNombre.getText().isEmpty() || campoCodigo.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    return true;
    } 
    
    public void actualizarTabla() {

        // Limpiar la tabla antes de agregar nuevos datos
        d.getModAsComercio().setRowCount(0);

        // Agregar los nuevos datos
        for (Comercio c: d.getListaZonas().get(posicion).getComerciosAsociados()) {
            
            d.agregarFilaAsComercio(c.getNombre(), c.getTipo(), c.getTelefono(), c.getEmail(), "Eliminar");
  
        }

        // Notificar a la tabla que los datos han cambiado
        d.getModAsComercio().fireTableDataChanged();
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComercio;
    private javax.swing.JTextField codigoZona;
    private javax.swing.JComboBox<String> comercio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JTextField nombreZona;
    private javax.swing.JButton salir;
    private javax.swing.JTable tAsociacionComercio;
    // End of variables declaration//GEN-END:variables
}
