/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.udc.asociacioncomercios.GUI.Frames;
/************************************************************************
Palabra de honor:
* No he discutido ni mostrado el código de mi programa con alguien que no sea mi compañero,
* Profesor o con el monitor asignado a este curso.
*
* No he utilizado código obtenido de otro u otros estudiantes,
* O cualquier otra fuente no autorizada, ya sea modificado o sin modificar.
*
* Si cualquier código o documentación utilizada en mi programa
* Fue obtenido de otra fuente, tal como un libro de texto o notas del curso
* debe ser claramente señalado con una cita apropiada en
* los comentarios de mi programa.
*
* <Luis Eduardo Julio Padilla - 0222020021>
*<Jesús David Blanco Julio -0222020019>
************************************************** *********************/

import com.udc.asociacioncomercios.app.Datos;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author cpala
 */
public class PaginaInicio extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    
    Datos d = Datos.getD();
    public PaginaInicio() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        botonGc = new javax.swing.JButton();
        botonGi = new javax.swing.JButton();
        botonGp = new javax.swing.JButton();
        botonGpr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonGz = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        clientesb = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        userButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        guardar = new javax.swing.JMenuItem();
        cargar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        botonGc.setText("Gestion comercios ");
        botonGc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGcActionPerformed(evt);
            }
        });

        botonGi.setText("Centro de Distribucion");
        botonGi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGiActionPerformed(evt);
            }
        });

        botonGp.setText("Gestion Pedidos ");
        botonGp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGpActionPerformed(evt);
            }
        });

        botonGpr.setText("Proveedores");
        botonGpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGprActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel1.setText("COMERSCA");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Asociacion de comercios del caribe");

        botonGz.setText("Zonas de Distribucion");
        botonGz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGzActionPerformed(evt);
            }
        });

        clientesb.setText("Gestion Clientes");
        clientesb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesbActionPerformed(evt);
            }
        });

        jButton1.setText("HOME");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        userButton.setText("USER");
        userButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });

        Archivo.setText("Archivo");

        guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        Archivo.add(guardar);

        cargar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cargar.setText("Cargar archivo");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });
        Archivo.add(cargar);

        jMenuBar1.add(Archivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonGc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(botonGi))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonGp, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonGpr, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientesb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(476, 476, 476))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(468, 468, 468))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(241, 241, 241))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(userButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(userButton)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGc)
                    .addComponent(botonGi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonGz))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGp, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGpr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientesb, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );

        userButton.getAccessibleContext().setAccessibleName("user");
        userButton.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        JPopupMenu menuEmergente = new JPopupMenu();

        // Agrega elementos a la lista emergente
        JMenuItem item1 = new JMenuItem("Cerrar Sesion");

        menuEmergente.add(item1);

        // Muestra la lista emergente en la posición del componente padre
        menuEmergente.show(userButton, 0, userButton.getHeight());     
        
                item1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Login l = new Login();
                l.setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_userButtonActionPerformed

    private void botonGcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGcActionPerformed
        PaginaGestionComercio gcom = new PaginaGestionComercio();
        gcom.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonGcActionPerformed

    private void botonGprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGprActionPerformed
       PaginaGestionProveedor gpr = new PaginaGestionProveedor();
        gpr.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonGprActionPerformed

    private void botonGzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGzActionPerformed
        PaginaGestionZonaDeDistribucion gz = new PaginaGestionZonaDeDistribucion();
        gz.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonGzActionPerformed

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
     // Crear un JFileChooser
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        // Mostrar el cuadro de diálogo de guardar archivo
        int seleccion = fileChooser.showSaveDialog(this);

        // Procesar la elección del usuario

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // Obtener la ruta del directorio seleccionado por el usuario
            String rutaDirectorio = fileChooser.getSelectedFile().getAbsolutePath();
            
            d.cargarComerciosDesdeArchivo(rutaDirectorio+ "/Comercios.txt");
            d.cargarZonasDesdeArchivo(rutaDirectorio+ "/ZonasDeDistribucion.txt");
            d.cargarProveedoresDesdeArchivo(rutaDirectorio+ "/Proveedores.txt");
            d.cargarClientesDesdeArchivo(rutaDirectorio+ "/Clientes.txt");
            d.cargarComerciantesDesdeArchivo(rutaDirectorio+ "/Comerciantes.txt");
            d.cargarProductosDesdeArchivo(rutaDirectorio+ "/Productos.txt");
            d.cargarAsociacionComerciosDesdeArchivo(rutaDirectorio+ "/AsignacionComerciosAZonas.txt");
            d.cargarPedidosDesdeArchivo(rutaDirectorio+"/Pedidos.txt");
            d.cargarAsociacionPedidosDesdeArchivo(rutaDirectorio+"/AsignacionProductosAPedidos.txt");
        }
     JOptionPane.showConfirmDialog(null, "Datos cargados exitosamente.", "COMERSCA", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_cargarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // Crear un JFileChooser
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        // Mostrar el cuadro de diálogo de guardar archivo
        int seleccion = fileChooser.showSaveDialog(this);

        // Procesar la elección del usuario

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // Obtener la ruta del directorio seleccionado por el usuario
            String rutaDirectorio = fileChooser.getSelectedFile().getAbsolutePath();

            d.guardarComercioEnArchivo(rutaDirectorio+ "/Comercios.txt");
            d.guardarZonasEnArchivo(rutaDirectorio+ "/ZonasDeDistribucion.txt");
            d.guardarProveedoresEnArchivo(rutaDirectorio+ "/Proveedores.txt");
            d.guardarClientesEnArchivo(rutaDirectorio+ "/Clientes.txt");
            d.guardarComerciantesEnArchivo(rutaDirectorio+ "/Comerciantes.txt");
            d.guardarProductosEnArchivo(rutaDirectorio+ "/Productos.txt");
            d.guardarAsociacionComerciosEnArchivo(rutaDirectorio+ "/AsignacionComerciosAZonas.txt");
            d.guardarPedidosEnArchivo(rutaDirectorio+"/Pedidos.txt");
            d.guardarAsociacionPedidosEnArchivo(rutaDirectorio+"/AsignacionProductosAPedidos.txt");
        }
     JOptionPane.showConfirmDialog(null, "Datos guardados exitosamente.", "COMERSCA", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_guardarActionPerformed

    private void botonGiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGiActionPerformed
       PaginaCentroDistribucion pcd = new PaginaCentroDistribucion();
       pcd.setVisible(true);
       dispose();
    }//GEN-LAST:event_botonGiActionPerformed

    private void botonGpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGpActionPerformed
       PaginaGestionPedido pgp = new PaginaGestionPedido();
       pgp.setVisible(true);
       dispose();
    }//GEN-LAST:event_botonGpActionPerformed

    private void clientesbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesbActionPerformed
       PaginaGestionClientes pcl = new PaginaGestionClientes();
       pcl.setVisible(true);
       dispose();
    }//GEN-LAST:event_clientesbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JButton botonGc;
    private javax.swing.JButton botonGi;
    private javax.swing.JButton botonGp;
    private javax.swing.JButton botonGpr;
    private javax.swing.JButton botonGz;
    private javax.swing.JMenuItem cargar;
    private javax.swing.JButton clientesb;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
